export const ListData = [
    {
        id: '1',
        src: '',
        firstName: "Ishwar",
        middle: "Ashok",
        lastName: "Deoolkar",
        mobileNumber: "7338502929",
        groups: ["Family", "Friends"]
    },
    {
        id: '2',
        src: '',
        firstName: "Ashwini",
        middleName: "Ishwar",
        lastName: "Deoolkar",
        mobileNumber: "7338503030",
        groups: ["Family", "Friends"]
    },
    {
        id: '3',
        src: '',
        firstName: "Vaishanvi",
        middleName: "Vasudev",
        lastName: "Deoolkar",
        mobileNumber: "7338502626",
        groups: ["Family"]
    },
    {
        id: '4',
        src: '',
        firstName: "Dattatray",
        middleName: "Vasudev",
        lastName: "Deoolkar",
        mobileNumber: "7338502525",
        groups: ["Family", "Office"],
    },
    {
        id: '5',
        src: '',
        firstName: 'Pavan',
        middleName: 'Dattatray',
        lastName: "Deoolkar",
        mobileNumber: "7338502424",
        groups: ["Family", "Office", "Friends"],
    },
    {
        id: '6',
        src: '',
        firstName: 'Pranali',
        middleName: 'Dattatray',
        lastName: "Deoolkar",
        mobileNumber: "7338502323",
        groups: ["Family", "Friends"],
    },
     {
        id: '7',
        src: '',
        firstName: "Sagar",
        middleName: "Ravikant",
        lastName: "Ghadi",
        mobileNumber: "7338502323",
        groups: ["Family", "Friends"],
    },
     {
        id: '8',
        src: '',
        firstName: 'Kiran',
        middleName: "Ravikant",
        lastName: "Ghadi",
        mobileNumber: "7338502323",
        groups: ["Family", "Friends"],
    },
     {
        id: '9',
        src: '',
        firstName: "Pramod",
        middleName: "Babalu",
        lastName: "Khare",
        mobileNumber: "7338502323",
        groups: ["Family", "Friends"],
    },
     {
        id: '10',
        src: '',
        firstName: "Rakesh",
        middleName: "N",
        lastName: "Gujar",
        mobileNumber: "7338502323",
        groups: ["Family", "Friends"],
    },
     {
        id: '11',
        src: '',
        firstName: "Anurag",
        middleName: "M",
        lastName: "Hugar",
        mobileNumber: "7338502323",
        groups: ["Family", "Friends"],
    },
     {
        id: '12',
        src: '',
        firstName: "Rajesh",
        middleName: "Vishnu",
        lastName: "Sharma",
        mobileNumber: "7338502323",
        groups: ["Family", "Friends"],
    },
];
